### ISSUE TITLE
[bump] Create tag for version 2.42.6

### ISSUE THREAD

**Issue by Spiker985** [pulsar-edit/autocomplete-plus#5]
### Have you checked for existing feature requests?

- [X] Completed

### Summary

.

### Enter your response below:

Allows us to use the new version within our package,json. Currently we are using Atom's v2.42.4, not 2.42.5 - however there have been some updates on our side

### Any alternatives?

.

**Comment by confused-Techie** [comment]
Sorry it's been so long for this PR. Let me go ahead and get on this, now that theres no more updates coming to this repo. I'll go ahead and close this once I get a PR merged into main for it. Thanks for pointing this out

**Comment by confused-Techie** [comment]
I've successfully created a tag for this release here, and added this bump to the main [`pulsar-edit/pulsar`](https://github.com/pulsar-edit/pulsar/pull/184) repo.

I'll go ahead and close this issue, as the original cause of it has been resolved. 

Thanks for contributing!
